title: "DataImpact"
author: "ascdata"
description: "Daten sichtbar machen, Wissen fördern, klüger entscheiden."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true         # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Blog, icon: newspaper, file: "index.html"}
  - {title: Über mich, icon: address-card, file: "about.md"}
  - {title: Buchempfehlungen, icon: book, file: "buchempfehlungen.md"}
  - {title: GitHub, icon: github, url: "https://github.com/ascdata"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/alexander-schaudin/"}
  - {title: Buy Me a Coffee, icon: mug-hot, url: "https://buymeacoffee.com/dataimpact"}
  #- {title: Impressum, icon: address-card, file: "impressum.md"}
  #- {title: Datenschutzerklärung, icon: address-card, file: "datenschutzerklärung.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  #- {title: Impressum, icon: address-card, file: "impressum.md"}
  #- {title: Datenschutzerklärung, icon: address-card, file: "datenschutzerklärung.md"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

footer:
  - title: "Impressum"
    file: "impressum.md"
