title: "ascdata.dev"
author: "ascdata"
description: "Passionate technologist with a keen focus on data engineering and visualization"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true         # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Blog, icon: book, file: "index.html"}
  - {title: About, icon: address-card, file: "about.md"}
  - {title: Github, icon: github, url: "https://github.com/ascdata"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/alexander-schaudin-63a351270/"}
  - {title: DataTalks, icon: mug-hot, url: "https://datatalks.club/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  # - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
